In [1]:
my_list = [1,2,3]

In [2]:
print(my_list)

[1, 2, 3]


In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)
#cASTING A lIST TO AN ARRAY

In [5]:
print(arr)

[1 2 3]


In [6]:
print(np)

<module 'numpy' from 'C:\\Users\\javee\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


In [7]:
type(arr)

numpy.ndarray

In [10]:
np.arange(0,10,2) #Rmember, arange. Also the Fucntion is Upto But not Including

array([0, 2, 4, 6, 8])

In [11]:
#Zeros Arrays
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3)) #2D Matrix, The Number of Matrices Determine the Number of Rows and Columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.linspace(0,5,10) #THird Argument is No Of Spaces You Want

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4) # This is an identity Matrice. Look at the Diagonal Matrice

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5) #Random Number of Floats in between 0 and 1

array([0.8565388 , 0.0837649 , 0.78313999, 0.71174824, 0.38049725])

In [17]:
np.random.rand(5,5) #Random Number of Floats in between 0 and 1. But this One is a 2d Matrice

array([[0.63549735, 0.81570439, 0.07779913, 0.31285129, 0.94098515],
       [0.48271974, 0.33969362, 0.26799833, 0.44401224, 0.20539004],
       [0.55452771, 0.57024703, 0.53631899, 0.05081317, 0.47433939],
       [0.85822468, 0.04131792, 0.89000417, 0.0114893 , 0.18073223],
       [0.21989541, 0.95659217, 0.33299225, 0.17133433, 0.74941564]])

In [19]:
np.random.randn(2) #This Number is Very Random

array([0.26816639, 0.6655977 ])

In [20]:
np.random.randint(1,100,10) #Inclusive on the Low End and Exclusive on the High End. Print 10 Only

array([43, 95, 40, 84, 41, 32, 94, 26, 34, 70])

In [24]:
arr.max()

3

In [25]:
arr.min()

1

In [26]:
arr

array([1, 2, 3])

In [27]:
#At What Index is the Max Value Located?
arr.argmax()

2

In [28]:
#What Index is The Minimum Located?
arr.argmin()

0

In [29]:
arr.shape()

TypeError: 'tuple' object is not callable

In [30]:
arr.shape

(3,)

In [2]:
import numpy as np
#learning Array indexing

In [5]:
arr = np.arange(0,11)

In [6]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [9]:
 #To Copy an array
array_copy = arr.copy()
    

In [10]:
array_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#In Numpy, If An array is directly referenced. THat means it is Creating a View but
#Not a Duplicat or a Copy.

#So While making Operations, Make Sure You are Making a Copy

In [12]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [13]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_3d[2]

NameError: name 'arr_3d' is not defined

In [15]:
arr_2d[2]

array([35, 40, 45])

In [16]:
#To Grab 40
arr_2d[2][2]

45

In [17]:
#shit 
arr_2d[2][1]

40

In [18]:
arr_2d[0]

array([ 5, 10, 15])

In [19]:
arr_2d[0][0]

5

In [20]:
arr[:2][1:] #First One is Rown and the Other is Column

array([1])

In [21]:
arr[:2]

array([0, 1])

In [22]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [23]:
arr_2d[:2][1:]

array([[20, 25, 30]])

In [24]:
arr_2d[1:][:2]

array([[20, 25, 30],
       [35, 40, 45]])

In [25]:
#Conditional Selection

In [27]:
arr2 = np.arange(1,11)

In [28]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr2 > 5 # Returns me a Boolean array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [30]:
bool_arr = arr2.copy

In [31]:
bool_arr = arr2.copy()

In [33]:
arr[arr>5] #Making an Array, Out of the Boolean array

array([ 6,  7,  8,  9, 10])

In [34]:
bool_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
bool_arr = arr>5

In [36]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [37]:
arr[bool_arr] #prints only the True Values

array([ 6,  7,  8,  9, 10])

In [38]:
#Numpy Operations

In [39]:
import numpy as np

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
#Add 2 Arrays together
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
#Same to all the basic arithmetics
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
arr + 100
#Adds 100 to every Element in the index

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [46]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [47]:
np.exp(arr) #Exponent Fucntion

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [48]:
np.log(arr)

C:\Users\javee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [50]:
np.sin(arr) #Sin Fucntion

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [51]:
arr = 5

In [52]:
arrr

NameError: name 'arrr' is not defined

In [53]:
arr

5

In [54]:
arr

5

In [55]:
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr = 5

In [58]:
arr

5

In [59]:
import numpy as np

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.ones(1)

array([1.])

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [64]:
arr = np.arange(10,51)

In [65]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [66]:
arr[::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [68]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
np.random.rand(1)

array([0.07716149])

In [71]:
np.random.randint

<function RandomState.randint>

In [72]:
np.random.randint(3)

2

In [73]:
np.random.randn(25) #randn is a Sample form Standard Deviations

array([ 0.47767157, -0.39595451, -0.72627636, -0.85489729,  1.11875133,
        0.53102251, -0.71690739, -1.09282958,  0.08278351,  0.33521826,
       -0.99480663, -1.40783303, -0.875028  , -0.15465867,  0.33089623,
        1.39960563, -0.71185278, -0.17936393, -0.21664908, -0.65391704,
        1.46870628,  0.55229059, -0.53347041,  1.40491536,  0.9518239 ])

In [76]:
 arr = np.arange(0,2)

In [77]:
arr

array([0, 1])

In [78]:
arr.reshape(2,2)

ValueError: cannot reshape array of size 2 into shape (2,2)

In [79]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [81]:
np.linspace(0.01,1,10)

array([0.01, 0.12, 0.23, 0.34, 0.45, 0.56, 0.67, 0.78, 0.89, 1.  ])

In [82]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [83]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [84]:
mat = np.arange(1,26).reshape(5,5)

In [97]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [102]:
mat[3,4]

20

In [103]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [104]:
mat[3,4]

20

In [105]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [95]:
mat[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [96]:
mat[2:][1:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [106]:
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [107]:
mat.sum()

325

In [108]:
mat.std()

7.211102550927978

In [109]:
mat[:,0:4].sum()

250

In [111]:
mat.sum(axis=0) #Remember This

array([55, 60, 65, 70, 75])